name: iot-stack
services:
    eclipse-mosquitto:
        container_name: mosquitto
        ports:
            - 1883:1883
            - 9001:9001
        restart: unless-stopped
        volumes:
            - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - mosquitto-data:/mosquitto/data
            - ./mosquitto/log:/mosquitto/log
        image: eclipse-mosquitto:latest
        environment:
            - TZ=Asia/Jakarta
    node-red:
        ports:
            - 1880:1880
        restart: unless-stopped
        volumes:
            - node-red-data:/data
        container_name: nodered
        image: nodered/node-red:latest
        environment:
            - TZ=Asia/Jakarta
    influxdb2:
        container_name: influxdb2
        ports:
            - 8086:8086
        volumes:
            - influxdb2-data:/var/lib/influxdb2
            - influxdb2-config:/etc/influxdb2
        restart: unless-stopped
        environment:
            - TZ=Asia/Jakarta
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
            - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
            - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG_NAME}
            - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET_NAME}
        image: influxdb:latest
    grafana:
        container_name: grafana
        image: grafana/grafana:latest
        restart: unless-stopped
        ports:
            - 3000:3000
        volumes:
            - grafana-storage:/var/lib/grafana
        environment:
            - TZ=Asia/Jakarta
            - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

volumes:
  node-red-data:
  mosquitto-data:
  influxdb2-data:
  influxdb2-config:
  grafana-storage: